### ISSUE TITLE
MySQL  DB4:3306 ssl  JS > proxy.configure() User-defined function threw an exception:  Traceback (most recent call last):   File "init.py", line 30, in <lambda>   File "/home/vilutuser/.mysqlsh/plugins/proxysql/proxysql.py", line 143, in configure     where member_host = 'vilreport14194.local' and member_role='PRIMARY'""") mysqlsh.DBError: MySQL Error (1267): ClassicSession.run_sql: Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8_general_ci,SYSCONST) for operation '='

### ISSUE THREAD

**Issue by AnishKuma** [lefred/mysqlshell-plugins#12]
MySQL Shell 8.0.22 and ProxySQL V 2.0.15

**Comment by lefred** [comment]
next time, try to split the issue title and the description. Could you provide more info related to the MySQL Server too ?

I just have committed a change, could you test it ?

**Comment by AnishKuma** [comment]
yes , it is working fine as per the changes suggested by you . Thanks for the quick support . Now we can able to configure ProxySQL via MySQl shell 8.0.22 with latest plugins . But the same kind of error is coming from proxySQL monitoring side .
proxySQL version : V 2.0.15
MySQL version : 8.0.22
Attaching the ProxySQL logs for your reference .
proxysql.zip
2020-11-30 13:21:16 MySQL_HostGroups_Manager.cpp:3832:update_group_replication_set_offline(): [WARNING] Group Replication: setting host vilreport14194.local:3307 offline because: viable_candidate=NO

We have noticed in SYS database in proxysql side like a view in sys database 'gr_member_routing_candidate_status' .

Function -- > gr_member_in_primary_partition .
[proxysql.zip](https://github.com/lefred/mysqlshell-plugins/files/5615364/proxysql.zip)

**Comment by arun741** [comment]
We also noticed the same for function sys.gr_member_in_primary_partition() line number 178.
we edited the function at mysql side and its working.

 result = session.run_sql("""CREATE FUNCTION sys.gr_member_in_primary_partition()
                    RETURNS VARCHAR(3)
                    DETERMINISTIC
                    BEGIN
                      RETURN (
                        select
                        if((select count(*) from performance_schema.replication_group_members
                               where MEMBER_STATE NOT IN ('ONLINE', 'RECOVERING')) <=
                            (select count(*) from performance_schema.replication_group_members)/2, "yes", "no") valid
                        **from performance_schema.replication_group_members where member_host=@@hostname);**
                    END""")
            result = session.run_sql("""DROP FUNCTION IF EXISTS sys.gr_transactions_behind""")

**Comment by lefred** [comment]
Thank you for the feedback, I modified it too. 

I'm closing the issue.
