### ISSUE TITLE
check.getSlowerQuery() + Y to see explain

### ISSUE THREAD

**Issue by wwwted** [lefred/mysqlshell-plugins#19]
Using latest build of plugins and MySQL 8.0.23 produts.

 MySQL  127.0.0.1:33110+ ssl  JS > check.getSlowerQuery()
*************************** 1. row ***************************
      schema_name: mysql
          tot_lat: 152.29 ms
       exec_count: 1
 latency_per_call: 152.29 ms
       first_seen: 2021-02-25 13:44:54.964195
        last_seen: 2021-02-25 13:44:54.964195
query_sample_text: SELECT BINARY T.table_name AS name, IF(ANY_VALUE(T.table_type) LIKE '%VIEW', IF(COUNT(*)=1 AND COUNT(CASE WHEN (column_name = 'doc' AND data_type = 'json') THEN 1 ELSE NULL END)=1, 'COLLECTION_VIEW', 'VIEW'), IF(COUNT(CASE WHEN (column_name != '_json_schema') THEN 1 ELSE NULL END)-2 = COUNT(CASE WHEN (column_name != '_id' AND column_name != 'doc' AND column_name != '_json_schema' AND generation_expression RLIKE 'json_extract\\(`doc`,(_[[:alnum:]]+)?\\\\''\\$((\\*{2})?(\\[([[:digit:]]+|\\*)\\]|\\.([[:alpha:]_\\$][[:alnum:]_\\$]*|\\*|\\".*\\"|`.*`)))*\\\\''\\)') THEN 1 ELSE NULL END) AND COUNT(CASE WHEN (column_name = 'doc' AND data_type = 'json') THEN 1 ELSE NULL END)=1 AND COUNT(CASE WHEN (column_name = '_id' AND generation_expression RLIKE '^json_unquote\\(json_extract\\(`doc`,(_[[:alnum:]]+)?\\\\''\\$\\._id\\\\''\\)\\)$') THEN 1 ELSE NULL END)=1, 'COLLECTION', 'TABLE')) AS type FROM information_schema.tables AS T LEFT JOIN information_schema.columns AS C ON (BINARY T.table_schema = C.table_schema AND BIN...
Do you want to have EXPLAIN output? (y/N) y
check.getSlowerQuery: User-defined function threw an exception: 
Traceback (most recent call last):
  File "/home/ted/.mysqlsh/plugins/check/queries.py", line 84, in get_queries_95_perc
    _get_full_details(shell, session, original_query, row[0])
  File "/home/ted/.mysqlsh/plugins/check/queries.py", line 18, in _get_full_details
    run_and_show(stmt,'vertical')
  File "/home/ted/.mysqlsh/plugins/mysqlsh_plugins_common.py", line 73, in run_and_show
    result = session.run_sql(stmt)
mysqlsh.DBError: MySQL Error (1064): Session.run_sql: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '..' at line 1
 (ScriptingError)

**Comment by lefred** [comment]
could you verify that `query_sample_text` is not truncated ?

**Comment by lefred** [comment]
See: https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html#sysvar_performance_schema_max_sql_text_length

**Comment by wwwted** [comment]
Makes sense, perhaps do not suggest "explain" when function return truncated SQL result or hint user about the option change sysvar_performance_schema_max_sql_text_length. Not sure if you can see if the SQL is truncated via PS, if not just look at sysvar_performance_schema_max_sql_text_length and length of printed SQL instead of throwing some nasty error code to users ;)

**Comment by lefred** [comment]
It makes sense, will check what I can implement, thx ;)
