### ISSUE TITLE
Clone user like mysqluserclone

### ISSUE THREAD

**Issue by gdsotirov** [lefred/mysqlshell-plugins#24]
This is more a question (or suggestion).

I see there is a function `user.copy` (see [user/copy.py](https://github.com/lefred/mysqlshell-plugins/blob/master/user/copy.py)), which according to its description is for _Copy[ing] a user to another server_. However, my aim is to _clone_ a user (e.g. create new user `user2` as `user1` also copying its grants either on the same or another server) like with the old `mysqluserclone` utility (see [scripts/mysqluserclone.py](https://github.com/mysql/mysql-utilities/blob/master/scripts/mysqluserclone.py)). I do not think this is possible currently (or is it)? If not possible then would you accept a suggestion for a `user.clone` function?

**Comment by lefred** [comment]
Hi, 
Nice suggestion, I will check and of course PR are always welcome !
Thank you for testing and contributing to Shell Plugins !

**Comment by gdsotirov** [comment]
I wrote `user.clone` function based on `user.copy`, which you could check in PR #26.
