### ISSUE TITLE
Is there a manual

### ISSUE THREAD

**Issue by peng19832** [lefred/mysqlshell-plugins#4]
![image](https://user-images.githubusercontent.com/9590209/71341785-cb563200-2595-11ea-8cde-8a7596351e94.png)
 MySQL  172.16.8.34:4306  JS > proxy=ext.proxysql.create('admin@127.0.0.1:6032')
Password: *****
Connected to ProxySQL (2.0.8-67-g877cab1)
{
    "configure": , 
    "connections": , 
    "getUsers": , 
    "hostgroups": , 
    "hosts": , 
    "importUsers": , 
    "setUser": , 
    "setUserHostgroup": , 
    "status": , 
    "version": 
}
 MySQL  172.16.8.34:4306  JS > proxy.configure()
**_ERROR: Please connect or provide a session to the Primary Master._**

**Comment by lefred** [comment]
Is 172.16.8.34 your primary master of your InnoDB Cluster ?

**Comment by lefred** [comment]
You can see how it works here: https://lefred.be/content/how-to-integrate-proxysql-in-mysql-innodb-cluster/

I use X protocol

**Comment by peng19832** [comment]
> You can see how it works here: https://lefred.be/content/how-to-integrate-proxysql-in-mysql-innodb-cluster/
> 
> I use X protocol

yes, 172.16.8.34 is primary.

**Comment by lefred** [comment]
please run `\s` and post the result here

**Comment by lefred** [comment]
And run this too: 
```
\sql select member_role from performance_schema.replication_group_members 
            where member_host = @@hostname and member_role='PRIMARY';
```

**Comment by peng19832** [comment]
![image](https://user-images.githubusercontent.com/9590209/71387947-30ab3100-2631-11ea-9220-357176347958.png)
![image](https://user-images.githubusercontent.com/9590209/71387964-41f43d80-2631-11ea-957e-05530cdfa1cc.png)
![image](https://user-images.githubusercontent.com/9590209/71388053-a9aa8880-2631-11ea-85ed-341cb4f7807e.png)

MySQL  172.16.8.34:4306  JS > \sql select member_role from performance_schema.replication_group_members where member_host = '172.16.8.34' and member_role='PRIMARY';
+-------------+
| member_role |
+-------------+
| PRIMARY     |
+-------------+
1 row in set (0.0015 sec)
 MySQL  172.16.8.34:4306  JS > \s
MySQL Shell version 8.0.18

Session type:                 Classic
Connection Id:                29566
Current schema:               
Current user:                 root@172.16.8.35
SSL:                          Not in use.
Using delimiter:              ;
Server version:               8.0.17 MySQL Community Server - GPL
Protocol version:             classic 10
Client library:               8.0.18
Connection:                   172.16.8.34 via TCP/IP
TCP port:                     4306
Server characterset:          utf8mb4
Schema characterset:          utf8mb4
Client characterset:          utf8mb4
Conn. characterset:           utf8mb4
Compression:                  Disabled
Uptime:                       16 hours 28 min 44.0000 sec

Threads: 9  Questions: 64191  Slow queries: 18  Opens: 200  Flush tables: 4  Open tables: 58  Queries per second avg: 1.082

MySQL  172.16.8.34:4306  JS > proxy=ext.proxysql.create('admin@127.0.0.1:6032')
Password: *****
Connected to ProxySQL (2.0.8-67-g877cab1)
{
    "configure": , 
    "connections": , 
    "getUsers": , 
    "hostgroups": , 
    "hosts": , 
    "importUsers": , 
    "setUser": , 
    "setUserHostgroup": , 
    "status": , 
    "version": 
}
 MySQL  172.16.8.34:4306  JS > proxy.configure()
ERROR: Please connect or provide a session to the Primary Master.

**Comment by lefred** [comment]
Thank you for the info, I will try to reproduce, meanwhile, could you maybe test this using the X protocol instead of the classic one ?

**Comment by peng19832** [comment]
yes，i tried X protocol

**Comment by peng19832** [comment]
Interestingly, if I manually create a monitor user, the plugin will tell me that the user already exists, but host information can be obtained using getHosts.However, if there is no monitor user, it will throw this error, and other functions and methods cannot obtain information.

**Comment by peng19832** [comment]
i found this.
2.0.8 not monitoring MGR in 8.0.18:
https://github.com/sysown/proxysql/issues/2432

then,i downgrade proxysql to 2.0.7，use plugin.proxysql.configure(), throw:
![image](https://user-images.githubusercontent.com/9590209/71499496-bc27fa80-289b-11ea-93f2-c2260c8126f5.png)

**Comment by lefred** [comment]
![Selection_097](https://user-images.githubusercontent.com/609675/71513450-af56d700-289a-11ea-9d40-3301bd63dfe8.png)

**Comment by lefred** [comment]
I see you are using the admin user of proxysql, you should create a remote one (not sure it's the problem)

**Comment by lefred** [comment]
I had to downgrade to 2.0.7 too to be able to see the status and use proxysql:
![Selection_098](https://user-images.githubusercontent.com/609675/71515024-88e86a00-28a1-11ea-9c50-89bde66d0b8d.png)

**Comment by lefred** [comment]
I tried using the classic protocol:
![Selection_099](https://user-images.githubusercontent.com/609675/71515085-cf3dc900-28a1-11ea-86a5-276340d66a3f.png)

**Comment by lefred** [comment]
But when I use the admin user like you did I've the same error. This is a limitation with the admin user allowing connection only from localhost in ProxySQL, that's why you **must create** another admin user as explained in the blog post:
In /etc/proxysql.cnf, you modify the admin_variable like this:
```
admin_credentials="admin:admin;radmin:fred" 
```
![Selection_100](https://user-images.githubusercontent.com/609675/71515149-2ba0e880-28a2-11ea-9ee6-0663111fa638.png)

**Comment by peng19832** [comment]
oh, thks for your reply.
Does it mean that I will not use admin@127.0.0.1?
Is this a mandatory restriction on the admin user, or a bug？
e.g：
mysqlsh --uri=clusterAdmin@172.16.8.34  <—— the primary
proxy=ext.proxysql.create('admin@127.0.0.1')  <—— connect local proxysql

**Comment by peng19832** [comment]
oh, thks for your reply.
Does it mean that I will not use admin@127.0.0.1?
Is this a mandatory restriction on the admin user, or a bug？
e.g：
mysqlsh --uri=clusterAdmin@172.16.8.34  <—— the primary
proxy=ext.proxysql.create('admin@127.0.0.1')  <—— connect local proxysql

**Comment by lefred** [comment]
it's a limitation, the admin user is hardcoded to only connect using localhost, please try with a new user.

**Comment by lefred** [comment]
![Selection_101](https://user-images.githubusercontent.com/609675/71518734-83e0e600-28b4-11ea-8917-1b1df5c6d6b1.png)

Now, the plugin performs a check
